pybo/views/mem_views.py
import os
from datetime import datetime
from flask import Blueprint, render_template,url_for,request
from werkzeug.utils import redirect

from pybo.models import MemberCurrent,MemberAlumni,Professor, Education, Career, ResearchPage
from pybo import db

from pybo.utils import save_image,delete_image, generate_unique_filename
from pybo.views.auth_views import login_required

bp = Blueprint('member',__name__,url_prefix='/Members')

#-------------------------------------------------------------
@bp.route('/Current_Student')
def MemberCurrentDef():
    memberCurrentList = MemberCurrent.query.order_by(MemberCurrent.create_date.desc())
    return render_template('Members/cur_stu.html',memberCurrentList=memberCurrentList)

@bp.route('/Current_Student/create',methods=['GET','POST'])
@login_required
def create_current_student():
    if request.method == 'POST':
        kname = request.form['kname']
        ename = request.form['ename']
        degree = request.form['degree']
        email = request.form['email']
        create_date = datetime.now()

        file = request.files['image']
        filename = generate_unique_filename()        
        # 파일 저장
        file_path = save_image(file,'member',filename)
        new_current_student = MemberCurrent(kname=kname,ename=ename,degree=degree,email=email,image_path=file_path,folder='member',create_date=create_date)

        db.session.add(new_current_student)
        db.session.commit()

        return redirect(url_for('member.MemberCurrentDef'))
    else:
        return render_template('Members/create_cur.html')


@bp.route('/Current_Student/modify/<int:member_id>',methods=('GET','POST'))
@login_required
def modify_cur(member_id):
    member = MemberCurrent.query.get_or_404(member_id)

    if request.method == 'POST':
        kname = request.form['kname']
        ename = request.form['ename']
        degree = request.form['degree']
        email = request.form['email']

        member.kname = kname
        member.ename = ename
        member.degree = degree
        member.email = email

        if 'image' in request.files:
            file = request.files['image']
            if file.filename != '':
                delete_image(member.folder,os.path.basename(member.image_path))
                filename = generate_unique_filename()
                file_path = save_image(file,'member',filename)
                member.image_path = file_path
        
        member.modify_date = datetime.now()
        db.session.commit()
        return redirect(url_for('member.MemberCurrentDef'))
    return render_template('Members/edit_cur.html',member=member)


@bp.route('/Current_Student/delete/<int:member_id>',methods=('GET','POST'))
@login_required
def delete_cur(member_id):
    member = MemberCurrent.query.get_or_404(member_id)
    delete_image(member.folder,os.path.basename(member.image_path))
    db.session.delete(member)
    db.session.commit()
    return redirect(url_for('member.MemberCurrentDef'))


#-------------------------------------------------------------

@bp.route('/Alumni')
def MemberAlumniDef():
    memberAlumniList = MemberAlumni.query.order_by(MemberAlumni.create_date.desc())
    return render_template('Members/alumni.html',memberAlumniList=memberAlumniList)

@bp.route('/Alumni/create',methods=['GET','POST'])
@login_required
def create_alumni():
    if request.method == 'POST':
        kname = request.form['kname']
        ename = request.form['ename']
        degree = request.form['degree']
        company = request.form['company']
        create_date = datetime.now()

        file = request.files['image']        
        filename = generate_unique_filename()        
        # 파일 저장
        file_path = save_image(file,'member',filename)
        new_al = MemberAlumni(kname=kname,ename=ename,degree=degree,company=company,image_path=file_path,folder='member',create_date=create_date)

        db.session.add(new_al)
        db.session.commit()

        return redirect(url_for('member.MemberAlumniDef'))
    else:
        return render_template('Members/create_al.html')
        

@bp.route('/Alumni/modify/<int:member_id>',methods=('GET','POST'))
@login_required
def modify_al(member_id):
    member = MemberAlumni.query.get_or_404(member_id)

    if request.method == 'POST':
        kname = request.form['kname']
        ename = request.form['ename']
        degree = request.form['degree']
        company = request.form['company']

        member.kname = kname
        member.ename = ename
        member.degree = degree
        member.company = company

        if 'image' in request.files:
            file = request.files['image']
            if file.filename != '':
                delete_image(member.folder,os.path.basename(member.image_path))
                filename=generate_unique_filename()
                file_path = save_image(file,'member',filename)
                member.image_path = file_path
        # folder는 create시 자동으로 설정되므로 굳이 건들 필요 없다
        member.modify_date = datetime.now()
        db.session.commit()
        return redirect(url_for('member.MemberAlumniDef'))
    return render_template('Members/edit_al.html',member=member)


@bp.route('/Alumni/delete/<int:member_id>',methods=('GET','POST'))
@login_required
def delete_al(member_id):
    member = MemberAlumni.query.get_or_404(member_id)
    delete_image(member.folder,os.path.basename(member.image_path))
    db.session.delete(member)
    db.session.commit()
    return redirect(url_for('member.MemberAlumniDef'))


#-------------------------------------------------------------

@bp.route('/Professor')
def MemberProfDef():
    professor = Professor.query.get_or_404(1)
    return render_template('Members/professor.html',professor=professor)



@bp.route('/Professor/modify/<int:prof_id>', methods=('GET', 'POST'))
@login_required
def modify_prof(prof_id):
    professor = Professor.query.get_or_404(prof_id)
    education = Education.query.filter_by(professor_id=professor.id).all()
    career = Career.query.filter_by(professor_id=professor.id).all()
    researchPage = ResearchPage.query.filter_by(professor_id=professor.id).all()

    if request.method == 'POST':
        department = request.form['department']
        phone = request.form['phone']
        email = request.form['email']
        office_phone = request.form['office_phone']
        kaddress = request.form['kaddress']
        eaddress = request.form['eaddress']

        professor.department = department
        professor.phone = phone
        professor.email = email
        professor.office_phone = office_phone
        professor.kaddress = kaddress
        professor.eaddress = eaddress

        professor.modify_date = datetime.now()

        for edu in education:
            edu_id = edu.id
            Eperiod = request.form['Eperiod_' + str(edu_id)]
            Eedegree = request.form['Eedegree_' + str(edu_id)]
            Ekdegree = request.form['Ekdegree_' + str(edu_id)]
            EedegreeDetail = request.form['EedegreeDetail_' + str(edu_id)]

            edu.period = Eperiod
            edu.edegree = Eedegree
            edu.kdegree = Ekdegree
            edu.edegreeDetail = EedegreeDetail

        for car in career:
            car_id = car.id
            Cperiod = request.form['Cperiod_' + str(car_id)]
            Ceposition = request.form['Ceposition_' + str(car_id)]
            Ckposition = request.form['Ckposition_' + str(car_id)]
            CepositionDetail = request.form['CepositionDetail_' + str(car_id)]

            car.period = Cperiod
            car.eposition = Ceposition
            car.kposition = Ckposition
            car.epositionDetail = CepositionDetail

        for research in researchPage:
            research_id = research.id
            Rurl_path = request.form['url_path_' + str(research_id)]
            Rpage = request.form['page_' + str(research_id)]

            research.url_path = Rurl_path
            research.page = Rpage

        db.session.commit()

        return redirect(url_for('member.MemberProfDef'))

    return render_template('Members/edit_prof.html', professor=professor, education=education, career=career, researchPage=researchPage)

@bp.route('/Professor/create_education/<int:prof_id>',methods=('GET','POST'))
@login_required
def create_education(prof_id):
    if request.method == 'POST':
        period = request.form['period']
        edegree = request.form['edegree']
        kdegree = request.form['kdegree']
        edegreeDetail = request.form['edegreeDetail']

        edu = Education(professor_id=prof_id,period=period,edegree=edegree,kdegree=kdegree,edegreeDetail=edegreeDetail)

        db.session.add(edu)
        db.session.commit()

        return redirect(url_for('member.MemberProfDef'))
    return render_template('Members/create_edu.html')

@bp.route('/Professor/delete_education/<int:edu_id>')
@login_required
def delete_education(edu_id):
    edu = Education.query.get_or_404(edu_id)
    db.session.delete(edu)
    db.session.commit()
    return redirect(url_for('member.modify_prof',prof_id=1))


@bp.route('/Professor/create_career/<int:prof_id>',methods=('GET','POST'))
@login_required
def create_career(prof_id):
    if request.method == 'POST':
        period = request.form['period']
        eposition = request.form['eposition']
        kposition = request.form['kposition']
        epositionDetail = request.form['epositionDetail']

        career = Career(professor_id=prof_id,period=period,eposition=eposition,kposition=kposition,epositionDetail=epositionDetail)

        db.session.add(career)
        db.session.commit()
        return redirect(url_for('member.MemberProfDef'))
    return render_template('Members/create_career.html')

@bp.route('Professor/delete_career/<int:career_id>')
@login_required
def delete_career(career_id):
    career = Career.query.get_or_404(career_id)
    db.session.delete(career)
    db.session.commit()
    return redirect(url_for('member.modify_prof',prof_id=1))

pybo/templates/Members/alumni.html
{% extends 'base.html' %}
{% block content %}
<!-- Masthead-->
<header class="masthead1 bg-members text-white text-center">
    <div class="container d-flex align-items-center flex-column">

        <!-- Masthead Heading-->
        <h1 class="masthead-heading1 text-uppercase mb-0">Alumni</h1>
        <!-- Icon Divider-->
        <div class="divider-custom divider-light">
            <div class="divider-custom-line"></div>
            <div class="divider-custom-icon"><i class="fas fa-star"></i></div>
            <div class="divider-custom-line"></div>
        </div>
        <!-- Masthead Subheading-->

    </div>
</header>
<section class="py-5 text-center container">
    {% if g.user %}
    <div class="btn-wrap mb-3 mg-top30px">
        <button class="button-19 add" role="button"><a href="{{url_for('member.create_alumni')}}">Add Members</a></button>
    </div>
    {% endif %}
    <!-- Doctor's Degree -->
    <div class="row g-3">
        <div class="text-left">
            <h3>Ph.D.</h3>
        </div>
        {% if memberAlumniList %}
        {% for member in memberAlumniList %}
        {% if member.degree=="Doctor's Degree" and member.image_path %}
        <div class="col-lg-3 col-md-6 col-sm-6 no-trans">
            <div class="card" style="width: 13rem;">
                {% if member.folder and member.image_path %}
                <img style="height:220px;" src="{{ url_for('static', filename='uploads/' + member.folder + '/' + member.image_path) }}"
                    class="card-img-top" alt="people">
                {% endif %}
                <div class="card-body bg-e5e5e5">
                    <p class="card-text">{{member.kname}}<br>{{member.ename}}<br><small>{{member.degree}}<br></small><br>
                        {% if g.user %}<a style="color: blue" href="{{url_for('member.modify_al', member_id=member.id)}}" class="btn btn-sm">Edit</a>{% endif %}
                    </p>
                </div>
            </div>
        </div>
        {% endif %}
        {% endfor %}
        {% endif %}
    </div>

    <div class="mb-3"></div>
    <!-- Master's Degree -->
    <div class="row g-3">
        <div class="text-left">
            <h3>M.S.</h3>
        </div>
        {% if memberAlumniList %}
        {% for member in memberAlumniList %}
        {% if member.degree=="Master's Degree" and member.image_path %}
        <div class="col-lg-3 col-md-6 col-sm-6 no-trans">
            <div class="card" style="width: 13rem;">
                {% if member.folder and member.image_path %}
                <img style="height:220px;" src="{{ url_for('static', filename='uploads/' + member.folder + '/' + member.image_path) }}"
                    class="card-img-top" alt="people">
                {% endif %}
                <div class="card-body bg-e5e5e5">
                    <p class="card-text">{{member.kname}}<br>{{member.ename}}<br><small>{{member.degree}}<br></small><br>
                        {% if g.user %}<a style="color: blue" href="{{url_for('member.modify_al', member_id=member.id)}}" class="btn btn-sm">Edit</a>{% endif %}
                    </p>
                </div>
            </div>
        </div>
        {% endif %}
        {% endfor %}
        {% endif %}
    </div>

    <div class="mb-3"></div>
    <!-- Undergraduate -->
    <div class="row g-3">
        <div class="text-left">
            <h3>Undergraduate</h3>
        </div>
        {% if memberAlumniList %}
        {% for member in memberAlumniList %}
        {% if member.degree=="Undergraduate" and member.image_path %}
        <div class="col-lg-3 col-md-6 col-sm-6 no-trans">
            <div class="card" style="width: 13rem;">
                {% if member.folder and member.image_path %}
                <img style="height:220px;" src="{{ url_for('static', filename='uploads/' + member.folder + '/' + member.image_path) }}"
                    class="card-img-top" alt="people">
                {% endif %}
                <div class="card-body bg-e5e5e5">
                    <p class="card-text">
                        {{member.kname}}<br>{{member.ename}}<br><small>{{member.degree}}<br>{{member.company}}</small><br>
                        {% if g.user %}<a style="color: blue" href="{{url_for('member.modify_al', member_id=member.id)}}" class="btn btn-sm">Edit</a>{% endif %}
                    </p>
                </div>
            </div>
        </div>
        {% endif %}
        {% endfor %}
        {% endif %}
    </div>

</section>

{% endblock %}

pybo/templates/Members/create_al.html
{% extends 'base.html' %}
{% block content %}
<!-- Masthead-->
<header class="masthead1 bg-members text-white text-center">
    <div class="container d-flex align-items-center flex-column">

        <!-- Masthead Heading-->
        <h1 class="masthead-heading1 text-uppercase mb-0">Add Alumni</h1>
        <!-- Icon Divider-->
        <div class="divider-custom divider-light">
            <div class="divider-custom-line"></div>
            <div class="divider-custom-icon"><i class="fas fa-star"></i></div>
            <div class="divider-custom-line"></div>
        </div>
        <!-- Masthead Subheading-->

    </div>
</header>

<section class="py-5 text-center container">
    <div class="row">
        <div class="col-lg-6 mx-auto">
            <h1 class="display-4">Add Alumni</h1>
            <form method="POST" enctype="multipart/form-data" action="{{ url_for('member.create_alumni') }}">
                <div class="mb-3">
                    <label for="kname" class="form-label">Korean Name</label>
                    <input {% if not g.user %}disabled{% endif %} type="text" class="form-control" id="kname" name="kname" required>
                </div>
                <div class="mb-3">
                    <label for="ename" class="form-label">English Name</label>
                    <input type="text" class="form-control" id="ename" name="ename" required>
                </div>
                <div class="mb-3">
                    <label for="degree" class="form-label">Degree</label>
                    <select class="form-select" id="degree" name="degree" required>
                        <option value="Doctor's Degree">Doctor's Degree</option>
                        <option value="Master's Degree">Master's Degree</option>
                        <option value="Undergraduate">Undergraduate</option>
                    </select>
                </div>
                <div class="mb-3">
                    <label for="company" class="form-label">Company</label>
                    <input type="text" class="form-control" id="company" name="company" required>
                </div>
                <div class="mb-3">
                    <label for="image" class="form-label">Image</label>
                    <input type="file" class="form-control" id="image" name="image" accept="image/*" required>
                </div>
                <div class="text-center">
                    <button type="submit" class="btn btn-primary">Add</button>
                </div>
            </form>
        </div>
    </div>
</section>



{% endblock %}

pybo/templates/Members/create_cur.html
{% extends 'base.html' %}
{% block content %}
<!-- Masthead-->
<header class="masthead1 bg-members text-white text-center">
    <div class="container d-flex align-items-center flex-column">

        <!-- Masthead Heading-->
        <h1 class="masthead-heading1 text-uppercase mb-0">Add Current Student</h1>
        <!-- Icon Divider-->
        <div class="divider-custom divider-light">
            <div class="divider-custom-line"></div>
            <div class="divider-custom-icon"><i class="fas fa-star"></i></div>
            <div class="divider-custom-line"></div>
        </div>
        <!-- Masthead Subheading-->

    </div>
</header>

<section class="py-5 text-center container">
    <div class="row">
        <div class="col-lg-6 mx-auto">
            <h1 class="display-4">Add Current Student</h1>
            <form method="POST" enctype="multipart/form-data" action="{{ url_for('member.create_current_student') }}">
                <div class="mb-3">
                    <label for="kname" class="form-label">Korean Name</label>
                    <input type="text" class="form-control" id="kname" name="kname" required>
                </div>
                <div class="mb-3">
                    <label for="ename" class="form-label">English Name</label>
                    <input type="text" class="form-control" id="ename" name="ename" required>
                </div>
                <div class="mb-3">
                    <label for="degree" class="form-label">Degree</label>
                    <select class="form-select" id="degree" name="degree" required>
                        <option value="Post Doctoral">Post Doctoral</option>
                        <option value="Doctor's Degree">Doctor's Degree</option>                        
                        <option value="Master's Degree">Master's Degree</option>
                        <option value="Undergraduate">Undergraduate</option>
                    </select>
                </div>
                <div class="mb-3">
                    <label for="email" class="form-label">Email</label>
                    <input type="email" class="form-control" id="email" name="email" required>
                </div>
                <div class="mb-3">
                    <label for="image" class="form-label">Image</label>
                    <input type="file" class="form-control" id="image" name="image" accept="image/*" required>
                </div>
                <div class="text-center">
                    <button type="submit" class="btn btn-primary">Add</button>
                </div>
            </form>
        </div>
    </div>
</section>


{% endblock %}

pybo/templates/Members/cur_stu.html
{% extends 'base.html' %}
{% block content %}
<!-- Masthead-->
<header class="masthead1 bg-members text-white text-center">
    <div class="container d-flex align-items-center flex-column">

        <!-- Masthead Heading-->
        <h1 class="masthead-heading1 text-uppercase mb-0">Current Students</h1>
        <!-- Icon Divider-->
        <div class="divider-custom divider-light">
            <div class="divider-custom-line"></div>
            <div class="divider-custom-icon"><i class="fas fa-star"></i></div>
            <div class="divider-custom-line"></div>
        </div>
        <!-- Masthead Subheading-->

    </div>
</header>
<section class="py-5 text-center container">
    
    {% if g.user %}
    <div class="btn-wrap mb-3 mg-top30px">
        <button class="button-19 add" role="button"><a href="{{url_for('member.create_current_student')}}">Add Members</a></button>
    </div>
    {% endif %}

    <div class="row g-3">
        <div class="text-left">
            <h3>P.D.</h3>
        </div>
        {% if memberCurrentList %}
        {% for member in memberCurrentList %}
        {% if member.degree=="Post Doctoral" and member.image_path%}
        <div class="col-lg-3 col-md-6 col-sm-6 no-trans">
            <div class="card" style="width: 13rem;">
                {% if member.folder and member.image_path %}
                <img style="height:220px;" src="{{ url_for('static', filename='uploads/' + member.folder + '/' + member.image_path) }}"
                    class="card-img-top" alt="people">
                {% endif %}
                <div class="card-body bg-e5e5e5">
                    <p class="card-text">
                        {{member.kname}}<br>{{member.ename}}<br><small>{{member.degree}}<br>{{member.email}}</small><br>
                        {% if g.user %}<a style="color: blue" href="{{url_for('member.modify_cur', member_id=member.id)}}" class="btn btn-sm">Edit</a>{% endif %}
                    </p>
                </div>
            </div>
        </div>
        {% endif %}
        {% endfor %}
        {% endif %}
    </div>
    

    <div class="row pt-5 g-3">
        <div class="text-left">
            <h3>Ph.D.</h3>
        </div>
        {% if memberCurrentList %}
        {% for member in memberCurrentList %}
        {% if member.degree=="Doctor's Degree" and member.image_path%}
        <div class="col-lg-3 col-md-6 col-sm-6 no-trans">
            <div class="card" style="width: 13rem;">
                {% if member.folder and member.image_path %}
                <img style="height:220px;" src="{{ url_for('static', filename='uploads/' + member.folder + '/' + member.image_path) }}"
                    class="card-img-top" alt="people">
                {% endif %}
                <div class="card-body bg-e5e5e5">
                    <p class="card-text">
                        {{member.kname}}<br>{{member.ename}}<br><small>{{member.degree}}<br>{{member.email}}</small><br>
                        {% if g.user %}<a style="color: blue" href="{{url_for('member.modify_cur', member_id=member.id)}}" class="btn btn-sm">Edit</a>{% endif %}
                    </p>
                </div>
            </div>
        </div>
        {% endif %}
        {% endfor %}
        {% endif %}
    </div>

    <div class="row pt-5 g-3">
        <div class="text-left">
            <h3>M.S.</h3>
        </div>
        {% if memberCurrentList %}
        {% for member in memberCurrentList %}
        {% if member.degree=="Master's Degree" and member.image_path %}
        <div class="col-lg-3 col-md-6 col-sm-6 no-trans">
            <div class="card" style="width: 13rem;">
                {% if member.folder and member.image_path %}
                <img style="height:220px;" src="{{ url_for('static', filename='uploads/' + member.folder + '/' + member.image_path) }}"
                    class="card-img-top" alt="people">
                {% endif %}
                <div class="card-body bg-e5e5e5">
                    <p class="card-text">
                        {{member.kname}}<br>{{member.ename}}<br><small>{{member.degree}}<br>{{member.email}}</small><br>
                        {% if g.user %}<a style="color: blue" href="{{url_for('member.modify_cur', member_id=member.id)}}" class="btn btn-sm">Edit</a>{% endif %}
                    </p>
                </div>
            </div>
        </div>
        {% endif %}
        {% endfor %}
        {% endif %}
    </div>

    <div class="row pt-5 g-3">
        <div class="text-left">
            <h3>Undergraduate</h3>
        </div>
        {% if memberCurrentList %}
        {% for member in memberCurrentList %}
        {% if member.degree=="Undergraduate" and member.image_path %}
        <div class="col-lg-3 col-md-6 col-sm-6 no-trans">
            <div class="card" style="width: 13rem;">
                {% if member.folder and member.image_path %}
                <img style="height:220px;" src="{{ url_for('static', filename='uploads/' + member.folder + '/' + member.image_path) }}"
                    class="card-img-top" alt="people">
                {% endif %}
                <div class="card-body bg-e5e5e5">
                    <p class="card-text">
                        {{member.kname}}<br>{{member.ename}}<br><small>{{member.degree}}<br>{{member.email}}</small><br>
                        {% if g.user %}<a style="color: blue" href="{{url_for('member.modify_cur', member_id=member.id)}}" class="btn btn-sm">Edit</a>{% endif %}
                    </p>
                </div>
            </div>
        </div>
        {% endif %}
        {% endfor %}
        {% endif %}
    </div>

</section>
{% endblock %}

pybo/templates/Members/edit_al.html
{% extends 'base.html' %}
{% block content %}
<header class="masthead1 bg-members text-white text-center">
    <div class="container d-flex align-items-center flex-column">

        <!-- Masthead Heading-->
        <h1 class="masthead-heading1 text-uppercase mb-0">Edit Alumni</h1>
        <!-- Icon Divider-->
        <div class="divider-custom divider-light">
            <div class="divider-custom-line"></div>
            <div class="divider-custom-icon"><i class="fas fa-star"></i></div>
            <div class="divider-custom-line"></div>
        </div>

    </div>
</header>

<div class="container mb-3">
    <h1>Edit Alumni</h1>
    <form method="POST" enctype="multipart/form-data" action="{{ url_for('member.modify_al', member_id=member.id) }}">
        <div class="mb-3">
            <label for="kname" class="form-label">Korean Name</label>
            <input type="text" class="form-control" id="kname" name="kname" value="{{ member.kname }}" required>
        </div>
        <div class="mb-3">
            <label for="ename" class="form-label">English Name</label>
            <input type="text" class="form-control" id="ename" name="ename" value="{{ member.ename }}" required>
        </div>
        <div class="mb-3">
            <label for="degree" class="form-label">Degree</label>
            <select class="form-select" id="degree" name="degree" required>
                <option value="Doctor's Degree" {% if member.degree == "Doctor's Degree" %}selected{% endif %}>Doctor's Degree</option>
                <option value="Master's Degree" {% if member.degree == "Master's Degree" %}selected{% endif %}>Master's Degree</option>
                <option value="Undergraduate" {% if member.degree == "Undergraduate" %}selected{% endif %}>Undergraduate</option>
            </select>
        </div>
        <div class="mb-3">
            <label for="company" class="form-label">Company</label>
            <input type="text" class="form-control" id="company" name="company" value="{{ member.company }}" required>
        </div>
        <div class="mb-3">
            <label for="image" class="form-label">Image</label>
            <input type="file" class="form-control" id="image" name="image" accept="image/*">
        </div>
        <button type="submit" class="btn btn-primary">Save Changes</button>
        <a href="javascript:void(0)" class="delete btn btn-primary" data-uri="{{url_for('member.delete_al',member_id=member.id)}}">delete</a>

    </form>
</div>


{% endblock %}
{% block script %}
<script type="text/javascript">
const delete_elements = document.getElementsByClassName("delete");
Array.from(delete_elements).forEach(function(element){
    element.addEventListener('click',function(){
        if(confirm("정말로 삭제하시겠습니까?")){
            location.href = this.dataset.uri;
        };
    });
});
</script>
{% endblock %}

pybo/templates/Members/edit_cur.html
{% extends 'base.html' %}
{% block content %}
<header class="masthead1 bg-members text-white text-center">
    <div class="container d-flex align-items-center flex-column">

        <!-- Masthead Heading-->
        <h1 class="masthead-heading1 text-uppercase mb-0">Edit Current Student</h1>
        <!-- Icon Divider-->
        <div class="divider-custom divider-light">
            <div class="divider-custom-line"></div>
            <div class="divider-custom-icon"><i class="fas fa-star"></i></div>
            <div class="divider-custom-line"></div>
        </div>

    </div>
</header>

<div class="container mb-3">
    <h1>Edit Current Student</h1>
    <form method="POST" enctype="multipart/form-data" action="{{ url_for('member.modify_cur', member_id=member.id) }}">
        <div class="mb-3">
            <label for="kname" class="form-label">Korean Name</label>
            <input type="text" class="form-control" id="kname" name="kname" value="{{ member.kname }}" required>
        </div>
        <div class="mb-3">
            <label for="ename" class="form-label">English Name</label>
            <input type="text" class="form-control" id="ename" name="ename" value="{{ member.ename }}" required>
        </div>
        <div class="mb-3">
            <label for="degree" class="form-label">Degree</label>
            <select class="form-select" id="degree" name="degree" required>
                <option value="Post Doctoral" {% if member.degree == "Post Doctoral" %}selected{% endif %}>Post Doctoral</option>
                <option value="Doctor's Degree" {% if member.degree == "Doctor's Degree" %}selected{% endif %}>Doctor's Degree</option>
                <option value="Master's Degree" {% if member.degree == "Master's Degree" %}selected{% endif %}>Master's Degree</option>
                <option value="Undergraduate" {% if member.degree == "Undergraduate" %}selected{% endif %}>Undergraduate</option>
            </select>
        </div>
        <div class="mb-3">
            <label for="email" class="form-label">Email</label>
            <input type="email" class="form-control" id="email" name="email" value="{{ member.email }}" required>
        </div>
        <div class="mb-3">
            <label for="image" class="form-label">Image</label>
            <input type="file" class="form-control" id="image" name="image" accept="image/*">
        </div>
        <button type="submit" class="btn btn-primary">Save Changes</button>
        <a href="javascript:void(0)" class="delete btn btn-primary" data-uri="{{url_for('member.delete_cur',member_id=member.id)}}">delete</a>

    </form>
</div>
{% endblock %}
{% block script %}
<script type="text/javascript">
const delete_elements = document.getElementsByClassName("delete");
Array.from(delete_elements).forEach(function(element){
    element.addEventListener('click',function(){
        if(confirm("정말로 삭제하시겠습니까?")){
            location.href = this.dataset.uri;
        };
    });
});
</script>
{% endblock %}