pybo/views/pub_views.py
from datetime import datetime
from flask import Blueprint, render_template, url_for,request
from werkzeug.utils import redirect

from pybo.models import Publications, NameTag
from pybo import db

bp = Blueprint('pub',__name__,url_prefix='/Publications')
from pybo.views.auth_views import login_required

@bp.route('/Publications_Domestic_Conferences')
def PubDomConfDef():
    publicationsList = Publications.query.order_by(Publications.date.desc())
    return render_template('Publications/pub_dom_conf.html',publicationsList=publicationsList)

@bp.route('/Publications_Domestic_Journals')
def PubDomJournDef():
    publicationsList = Publications.query.order_by(Publications.date.desc())
    return render_template('Publications/pub_dom_journ.html',publicationsList=publicationsList)

@bp.route('/Publications_Domestic_Patents')
def PubDomPatenDef():
    publicationsList = Publications.query.order_by(Publications.date.desc())
    return render_template('Publications/pub_dom_paten.html',publicationsList=publicationsList)



@bp.route('/Publications_International_Conferences')
def PubInConfDef():
    publicationsList = Publications.query.order_by(Publications.date.desc())
    return render_template('Publications/pub_in_conf.html',publicationsList=publicationsList)

@bp.route('/Publications_International_Journals')
def PubInJournDef():
    publicationsList = Publications.query.order_by(Publications.date.desc())    
    return render_template('Publications/pub_in_journ.html',publicationsList=publicationsList)

@bp.route('/Publications_International_Patents')
def PubInPatenDef():
    publicationsList = Publications.query.order_by(Publications.date.desc())
    return render_template('Publications/pub_in_paten.html',publicationsList=publicationsList)


@bp.route('/Publications/create',methods=['GET','POST'])
@login_required
def create_publication():
    if request.method == 'POST':
        date = request.form['date']
        title = request.form['title']
        author = request.form['author']
        read_more = request.form['read_more']
        category = request.form['category']
        create_date = datetime.now()

        new_pub = Publications(date=date,title=title,author=author,read_more=read_more,category=category,create_date=create_date)
        db.session.add(new_pub)
        db.session.commit()


        # 각각의 생성 페이지로 rendering 되면 좋긴한데
        # 지금 상태를 보니 type 이랑 category를 설정했으면 가능했을듯 한데 지금 상태에서는 그냥 하기
        # 아래처럼 짜보면 되긴 할듯
        # if request.method == 'POST':
        # 데이터베이스에 새로운 항목 추가하는 코드
        # publication_type = request.form['type']  # 선택한 종류
        # publication_category = request.form['category']  # 선택한 카테고리
        # URL을 기반으로 템플릿 파일의 경로 생성
        # publication_path = url_for('static', filename=f'Publications/pub_{publication_type}_{publication_category}.html')
        # return render_template(publication_path)

        _next = request.args.get('next','')
        if _next:
            return redirect(_next)
        else:
            return redirect(url_for('pub.PubInJournDef'))
    
    previous_url = request.referrer
    return render_template('Publications/create_pub.html',previous_url=previous_url)
    
@bp.route('/Publications/modify/<int:pub_id>',methods=('GET','POST'))
@login_required
def modify(pub_id):
    publications = Publications.query.get_or_404(pub_id)
    if request.method == 'POST':
        date = request.form['date']
        title = request.form['title']
        author = request.form['author']
        read_more = request.form['read_more']
        category = request.form['category']

        publications.date = date
        publications.title = title
        publications.author = author
        publications.read_more = read_more
        publications.category = category
        publications.modify_date = datetime.now()
        db.session.commit()
        return redirect(url_for('pub.PubInJournDef'))
    return render_template('Publications/edit_pub.html',publications=publications)

@bp.route('/Publications/delete/<int:pub_id>')
@login_required
def delete(pub_id):
    publications = Publications.query.get_or_404(pub_id)
    db.session.delete(publications)
    db.session.commit()
    return redirect(url_for('pub.PubInJournDef'))

@bp.route('/publications/<int:pub_id>/add_nametag',methods=('GET','POST'))
@login_required
def add_nametag(pub_id):
    publication = Publications.query.get_or_404(pub_id)
    next = request.args.get('next')
    if request.method == 'POST':
        name = request.form['name']

        create_date = datetime.now()
        modify_date = datetime.now()

        nametag = NameTag(user_name=name,publication_id=pub_id,create_date=create_date,modify_date=modify_date)
        db.session.add(nametag)
        db.session.commit()
        if next:
            return redirect(next)
        return redirect(url_for('pub.PubInJournDef'))
    return render_template('Publications/add_nametag.html',publication=publication)

@bp.route('/publications/<int:pub_id>/edit_nametag',methods=['GET'])
@login_required
def view_nametag(pub_id):
    publication = Publications.query.get_or_404(pub_id)
    nametags = NameTag.query.filter_by(publication_id=pub_id).all()

    return render_template('Publications/view_nametags.html',publication=publication,nametags=nametags)

@bp.route('/publications/<int:pub_id>/edit_nametag/<int:nametag_id>',methods=('GET','POST'))
@login_required
def edit_nametag(pub_id,nametag_id):
    publication = Publications.query.get_or_404(pub_id)
    nametag = NameTag.query.get_or_404(nametag_id)

    if request.method == 'POST':
        name = request.form['user_name']

        nametag.user_name = name
        nametag.modify_date = datetime.now()

        db.session.commit()

        return redirect(url_for('pub.PubInJournDef'))
    return render_template('Publications/edit_nametag.html',publication=publication,nametag=nametag)

@bp.route('/publications/<int:pub_id>/delete_nametag/<int:nametag_id>', methods=['POST'])
@login_required
def delete_nametag(pub_id, nametag_id):
    nametag = NameTag.query.get_or_404(nametag_id)
    
    db.session.delete(nametag)
    db.session.commit()

    return redirect(url_for('pub.view_nametag', pub_id=pub_id))

pybo/templates/Publications/edit_nametag.html
{% extends 'base.html' %}
{% block content %}
<header class="masthead1 bg-publication text-white text-center">
    <div class="container d-flex align-items-center flex-column">

        <!-- Masthead Heading-->
        <h1 class="masthead-heading1 text-uppercase mb-0">Edit NameTags</h1>
        <!-- Icon Divider-->
        <div class="divider-custom divider-light">
            <div class="divider-custom-line"></div>
            <div class="divider-custom-icon"><i class="fas fa-star"></i></div>
            <div class="divider-custom-line"></div>
        </div>

    </div>
</header>
<section class="py-5 text-center container">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-8">
                <h1 class="display-4">Edit {{nametag.user_name}}</h1>
                <form method="post">
                    <div class="form-group">
                        <label for="user_name">Name</label>
                        <input type="text" class="form-control" id="user_name" name="user_name" required value="{{ nametag.user_name }}">
                    </div>
                    <input type="submit" value="저장">
                </form>
                <form action="{{url_for('pub.delete_nametag', pub_id=publication.id, nametag_id=nametag.id)}}" method="post" onsubmit="return confirm('정말 삭제하시겠습니까?');">
                    <input type="submit" value="Delete">
                </form>
            </div>
        </div>
    </div>
</section>
{% endblock %}

pybo/templates/Publications/pub_dom_conf.html
{% extends 'base.html' %}
{% block content %}
<!-- Masthead-->
<header class="masthead1 bg-publication text-white text-center">
    <div class="container d-flex align-items-center flex-column">

        <!-- Masthead Heading-->
        <!-- 경로 넣어주기... 각 페이지에 맞게끔 -->
        <h1 class="masthead-heading1 text-uppercase mb-0">Domestic Conferences</h1>
        <!-- Icon Divider-->
        <div class="divider-custom divider-light">
            <div class="divider-custom-line"></div>
            <div class="divider-custom-icon"><i class="fas fa-star"></i></div>
            <div class="divider-custom-line"></div>
        </div>

    </div>
</header>
<section class="py-5 text-center container">
    {% if g.user %}
    <div class="btn-wrap mb-3 mg-top30px">
        <button class="button-19 add" role="button"><a href="{{url_for('pub.create_publication')}}">Add Publications</a></button>
    </div>

    {% endif %}

    <!--list group-->
    {% if g.user %}
    <!-- Publications list group -->
<div class="container">
    <ul class="list-group list-group-horizontal">
        <li class="list-group-item list-group-item-action list-group-item-myself ul-li-width flex-fill"><a
                href="{{url_for('pub.PubInJournDef', _external=True)}}">International Journals</a></li>
        <li class="list-group-item list-group-item-action list-group-item-myself ul-li-width flex-fill"><a
                href="{{url_for('pub.PubInConfDef', _external=True)}}">International Conferences</a></li>
        <li class="list-group-item list-group-item-action list-group-item-myself ul-li-width flex-fill"><a
                href="{{url_for('pub.PubInPatenDef', _external=True)}}">International Patents</a></li>
    </ul>
    <ul class="list-group list-group-horizontal">
        <li class="list-group-item list-group-item-action list-group-item-myself ul-li-width flex-fill" ><a
                href="{{url_for('pub.PubDomJournDef', _external=True)}}">Domestic Journals</a></li>
        <li
            class="list-group-item list-group-item-action list-group-item-myself ul-li-width flex-fill list-group-item-myself-bgcolor">
            <a href="{{url_for('pub.PubDomConfDef', _external=True)}}">Domestic Conferences</a>
        </li>
        <li class="list-group-item list-group-item-action list-group-item-myself ul-li-width flex-fill"><a
                href="{{url_for('pub.PubDomPatenDef', _external=True)}}">Domestic Patents</a></li>
    </ul>
</div>
    {% endif %}

    <div class="container mg-top30px">
        <h1 class="text-left border-bottom">Domestic Conferences</h1>
        <div class="row">
            {% if publicationsList %}
            {% for publication in publicationsList %}
            {% if publication.category == "Domestic Conferences" %}
            <div class="col-12 mb-4">
                <div class="card h-100">
                    <div class="card-body text-start">
                        <h5 class="card-title">
                            <a href="{{ publication.read_more }}" class="text-decoration-none" style="color: black;">
                                {{ publication.title }}
                            </a>
                        </h5>
                        
                        {%if g.user %}
                        <ul class="name-tag-list">
                            {% for name_tag in publication.name_tags %}
                            <li>{{name_tag.user_name}}</li>
                            {% endfor %}
                        </ul>
                    <p style="border-bottom:3px solid darkgray !important;"><a href="{{url_for('pub.view_nametag',pub_id=publication.id)}}">Edit Name Tags</a></p>
                    {% else %}

                        <ul class="name-tag-list">
                            {% for name_tag in publication.name_tags %}
                            <li>{{name_tag.user_name}}</li>
                            {% endfor %}
                        </ul>

                    {% endif %}
                    <!-- author -> 컨퍼런스나 저널 이름 -->
                    <h6 class="card-subtitle mb-2 text-muted">{{publication.author}} | {{publication.date}}</h6>

                    {% if g.user %}
                    <a href="{{url_for('pub.modify', pub_id=publication.id)}}" class="btn btn-secondary">Edit</a>
                    {% endif %}
                    </div>
                </div>
            </div>
            {% endif %}
            {% endfor %}
            {% endif %}
        </div>
    </div>
    

</section>
{% endblock %}

pybo/templates/Publications/pub_dom_journ.html
{% extends 'base.html' %}
{% block content %}
<!-- Masthead-->
<header class="masthead1 bg-publication text-white text-center">
    <div class="container d-flex align-items-center flex-column">

        <!-- Masthead Heading-->
        <!-- 경로 넣어주기... 각 페이지에 맞게끔 -->
        <h1 class="masthead-heading1 text-uppercase mb-0">Domestic Journals</h1>
        <!-- Icon Divider-->
        <div class="divider-custom divider-light">
            <div class="divider-custom-line"></div>
            <div class="divider-custom-icon"><i class="fas fa-star"></i></div>
            <div class="divider-custom-line"></div>
        </div>

    </div>
</header>
<section class="py-5 text-center container">
    {% if g.user %}
    <div class="btn-wrap mb-3 mg-top30px">
        <button class="button-19 add" role="button"><a href="{{url_for('pub.create_publication')}}">Add Publications</a></button>
    </div>
    {% endif %}
    <!--list group-->
    {% if g.user %}
        <!-- Publications list group -->
<div class="container">
    <ul class="list-group list-group-horizontal">
        <li class="list-group-item list-group-item-action list-group-item-myself ul-li-width flex-fill"><a
                href="{{url_for('pub.PubInJournDef', _external=True)}}">International Journals</a></li>
        <li class="list-group-item list-group-item-action list-group-item-myself ul-li-width flex-fill"><a
                href="{{url_for('pub.PubInConfDef', _external=True)}}">International Conferences</a></li>
        <li class="list-group-item list-group-item-action list-group-item-myself ul-li-width flex-fill"><a
                href="{{url_for('pub.PubInPatenDef', _external=True)}}">International Patents</a></li>
    </ul>
    <ul class="list-group list-group-horizontal">
        <li class="list-group-item list-group-item-action list-group-item-myself ul-li-width flex-fill list-group-item-myself-bgcolor" ><a
                href="{{url_for('pub.PubDomJournDef', _external=True)}}">Domestic Journals</a></li>
        <li
            class="list-group-item list-group-item-action list-group-item-myself ul-li-width flex-fill">
            <a href="{{url_for('pub.PubDomConfDef', _external=True)}}">Domestic Conferences</a>
        </li>
        <li class="list-group-item list-group-item-action list-group-item-myself ul-li-width flex-fill"><a
                href="{{url_for('pub.PubDomPatenDef', _external=True)}}">Domestic Patents</a></li>
    </ul>
</div>
    {% endif %}

    <div class="container mg-top30px">
        <h1 class="text-left border-bottom">Domestic Journals</h1>
        <div class="row">
            {% if publicationsList %}
            {% for publication in publicationsList %}
            {% if publication.category == "Domestic Journals" %}
            <div class="col-12 mb-4">
                <div class="card h-100">
                    <div class="card-body text-start">
                        <h5 class="card-title">
                            <a href="{{ publication.read_more }}" class="text-decoration-none" style="color: black;">
                                {{ publication.title }}
                            </a>
                        </h5>
                        {%if g.user %}
                            <ul class="name-tag-list">
                                {% for name_tag in publication.name_tags %}
                                <li>{{name_tag.user_name}}</li>
                                {% endfor %}
                            </ul>
                        <p style="border-bottom:3px solid darkgray !important;"><a href="{{url_for('pub.view_nametag',pub_id=publication.id)}}">Edit Name Tags</a></p>
                        {% else %}

                            <ul class="name-tag-list">
                                {% for name_tag in publication.name_tags %}
                                <li>{{name_tag.user_name}}</li>
                                {% endfor %}
                            </ul>

                        {% endif %}
                        <!-- author -> 컨퍼런스나 저널 이름 -->
                        <h6 class="card-subtitle mb-2 text-muted">
                            {{ publication.author }} | {{ publication.date }}
                        </h6>

                        {% if g.user %}
                        <a href="{{ url_for('pub.modify', pub_id=publication.id) }}" class="btn btn-secondary">Edit</a>
                        {% endif %}
                    </div>
                </div>
            </div>
            {% endif %}
            {% endfor %}
            {% endif %}
        </div>
    </div>
    
</section>
{% endblock %}

pybo/templates/Publications/pub_dom_paten.html
{% extends 'base.html' %}
{% block content %}
<!-- Masthead-->
<header class="masthead1 bg-publication text-white text-center">
    <div class="container d-flex align-items-center flex-column">

        <!-- Masthead Heading-->
        <!-- 경로 넣어주기... 각 페이지에 맞게끔 -->
        <h1 class="masthead-heading1 text-uppercase mb-0">Domestic Patents</h1>
        <!-- Icon Divider-->
        <div class="divider-custom divider-light">
            <div class="divider-custom-line"></div>
            <div class="divider-custom-icon"><i class="fas fa-star"></i></div>
            <div class="divider-custom-line"></div>
        </div>

    </div>
</header>
<section class="py-5 text-center container">
    {% if g.user %}
    <div class="btn-wrap mb-3 mg-top30px">
        <button class="button-19 add" role="button"><a href="{{url_for('pub.create_publication')}}">Add Publications</a></button>
    </div>
    {% endif %}
    <!--list group-->
    {% if g.user %}
    <div class="container">
        <ul class="list-group list-group-horizontal">
            <li class="list-group-item list-group-item-action list-group-item-myself ul-li-width flex-fill"><a
                    href="{{url_for('pub.PubInJournDef', _external=True)}}">International Journals</a></li>
            <li class="list-group-item list-group-item-action list-group-item-myself ul-li-width flex-fill"><a
                    href="{{url_for('pub.PubInConfDef', _external=True)}}">International Conferences</a></li>
            <li class="list-group-item list-group-item-action list-group-item-myself ul-li-width flex-fill"><a
                    href="{{url_for('pub.PubInPatenDef', _external=True)}}">International Patents</a></li>
        </ul>
        <ul class="list-group list-group-horizontal">
            <li class="list-group-item list-group-item-action list-group-item-myself ul-li-width flex-fill" ><a
                    href="{{url_for('pub.PubDomJournDef', _external=True)}}">Domestic Journals</a></li>
            <li
                class="list-group-item list-group-item-action list-group-item-myself ul-li-width flex-fill">
                <a href="{{url_for('pub.PubDomConfDef', _external=True)}}">Domestic Conferences</a>
            </li>
            <li class="list-group-item list-group-item-action list-group-item-myself ul-li-width flex-fill list-group-item-myself-bgcolor"><a
                    href="{{url_for('pub.PubDomPatenDef', _external=True)}}">Domestic Patents</a></li>
        </ul>
    </div>
    {% endif %}

    <div class="container mg-top30px">
        <h1 class="text-left border-bottom">Domestic Patents</h1>
        <div class="row">
            {% if publicationsList %}
            {% for publication in publicationsList %}
            {% if publication.category == "Domestic Patents" %}
            <div class="col-12 mb-4">
                <div class="card h-100">
                    <div class="card-body text-start">
                        <h5 class="card-title">
                            <a href="{{ publication.read_more }}" class="text-decoration-none" style="color: black;">
                                {{ publication.title }}
                            </a>
                        </h5>
                        {%if g.user %}
                        <ul class="name-tag-list">
                            {% for name_tag in publication.name_tags %}
                            <li>{{name_tag.user_name}}</li>
                            {% endfor %}
                        </ul>
                    <p style="border-bottom:3px solid darkgray !important;"><a href="{{url_for('pub.view_nametag',pub_id=publication.id)}}">Edit Name Tags</a></p>
                    {% else %}

                        <ul class="name-tag-list">
                            {% for name_tag in publication.name_tags %}
                            <li>{{name_tag.user_name}}</li>
                            {% endfor %}
                        </ul>

                    {% endif %}
                    <!-- author -> 컨퍼런스나 저널 이름 -->
                    <h6 class="card-subtitle mb-2 text-muted">{{publication.author}} | {{publication.date}}</h6>

                    {% if g.user %}
                    <a href="{{url_for('pub.modify', pub_id=publication.id)}}" class="btn btn-secondary">Edit</a>
                    {% endif %}
                    </div>
                </div>
            </div>
            {% endif %}
            {% endfor %}
            {% endif %}
        </div>
    </div>
</section>

{% endblock %}

pybo/templates/Publications/pub_in_conf.html
{% extends 'base.html' %}
{% block content %}
<!-- Masthead-->
<header class="masthead1 bg-publication text-white text-center">
    <div class="container d-flex align-items-center flex-column">

        <!-- Masthead Heading-->
        <!-- 경로 넣어주기... 각 페이지에 맞게끔 -->
        <h1 class="masthead-heading1 text-uppercase mb-0">International Conferences</h1>
        <!-- Icon Divider-->
        <div class="divider-custom divider-light">
            <div class="divider-custom-line"></div>
            <div class="divider-custom-icon"><i class="fas fa-star"></i></div>
            <div class="divider-custom-line"></div>
        </div>

    </div>
</header>
<section class="py-5 text-center container">
    {% if g.user %}
    <div class="btn-wrap mb-3 mg-top30px">
        <button class="button-19 add" role="button"><a href="{{url_for('pub.create_publication')}}">Add Publications</a></button>
    </div>
    {% endif %}
    <!--list group-->
    {% if g.user %}
    <div class="container">
        <ul class="list-group list-group-horizontal">
            <li class="list-group-item list-group-item-action list-group-item-myself ul-li-width flex-fill"><a
                    href="{{url_for('pub.PubInJournDef', _external=True)}}">International Journals</a></li>
            <li class="list-group-item list-group-item-action list-group-item-myself ul-li-width flex-fill list-group-item-myself-bgcolor"><a
                    href="{{url_for('pub.PubInConfDef', _external=True)}}">International Conferences</a></li>
            <li class="list-group-item list-group-item-action list-group-item-myself ul-li-width flex-fill"><a
                    href="{{url_for('pub.PubInPatenDef', _external=True)}}">International Patents</a></li>
        </ul>
        <ul class="list-group list-group-horizontal">
            <li class="list-group-item list-group-item-action list-group-item-myself ul-li-width flex-fill" ><a
                    href="{{url_for('pub.PubDomJournDef', _external=True)}}">Domestic Journals</a></li>
            <li
                class="list-group-item list-group-item-action list-group-item-myself ul-li-width flex-fill">
                <a href="{{url_for('pub.PubDomConfDef', _external=True)}}">Domestic Conferences</a>
            </li>
            <li class="list-group-item list-group-item-action list-group-item-myself ul-li-width flex-fill"><a
                    href="{{url_for('pub.PubDomPatenDef', _external=True)}}">Domestic Patents</a></li>
        </ul>
    </div>
    {% endif %}

    <div class="container mg-top30px">
        <h1 class="text-left border-bottom">International Conferences</h1>
        <div class="row">
            {% if publicationsList %}
            {% for publication in publicationsList %}
            {% if publication.category == "International Conferences" %}
            <div class="col-12 mb-4">
                <div class="card h-100">
                    <div class="card-body text-start">
                        <h5 class="card-title"><a href="{{ publication.read_more }}" class="text-decoration-none" style="color: black;">{{ publication.title }}</a></h5>
                        
                        {% if g.user %}
                        <ul class="name-tag-list">
                            {% for name_tag in publication.name_tags %}
                            <li>{{ name_tag.user_name }}</li>
                            {% endfor %}
                        </ul>
                        <p style="border-bottom:3px solid darkgray !important;"><a href="{{url_for('pub.view_nametag',pub_id=publication.id)}}">Edit Name Tags</a></p>
                        {% else %}
                        <ul class="name-tag-list">
                            {% for name_tag in publication.name_tags %}
                            <li>{{ name_tag.user_name }}</li>
                            {% endfor %}
                        </ul>
                        {% endif %}
                        <!-- author -> 컨퍼런스나 저널 이름 -->
                        <h6 class="card-subtitle mb-2 text-muted">{{ publication.author }} | {{ publication.date }}</h6>

                        {% if g.user %}
                        <a href="{{ url_for('pub.modify', pub_id=publication.id) }}" class="btn btn-secondary">Edit</a>
                        {% endif %}
                    </div>
                </div>
            </div>
            {% endif %}
            {% endfor %}
            {% endif %}
        </div>
    </div>
    
</section>

{% endblock %}

pybo/templates/Publications/pub_in_journ.html
{% extends 'base.html' %}
{% block content %}
<!-- Masthead-->
<header class="masthead1 bg-publication text-white text-center">
    <div class="container d-flex align-items-center flex-column">

        <!-- Masthead Heading-->
        <!-- 경로 넣어주기... 각 페이지에 맞게끔 -->
        <h1 class="masthead-heading1 text-uppercase mb-0">International Journals</h1>
        <!-- Icon Divider-->
        <div class="divider-custom divider-light">
            <div class="divider-custom-line"></div>
            <div class="divider-custom-icon"><i class="fas fa-star"></i></div>
            <div class="divider-custom-line"></div>
        </div>

    </div>
</header>
<section class="py-5 text-center container">
    {% if g.user %}
    <div class="btn-wrap mb-3 mg-top30px">
        <button class="button-19 add" role="button"><a href="{{url_for('pub.create_publication')}}">Add Publications</a></button>
    </div>
    {% endif %}
    <!--list group-->
    {% if g.user %}
    <div class="container">
        <ul class="list-group list-group-horizontal">
            <li class="list-group-item list-group-item-action list-group-item-myself ul-li-width flex-fill list-group-item-myself-bgcolor"><a
                    href="{{url_for('pub.PubInJournDef', _external=True)}}">International Journals</a></li>
            <li class="list-group-item list-group-item-action list-group-item-myself ul-li-width flex-fill"><a
                    href="{{url_for('pub.PubInConfDef', _external=True)}}">International Conferences</a></li>
            <li class="list-group-item list-group-item-action list-group-item-myself ul-li-width flex-fill"><a
                    href="{{url_for('pub.PubInPatenDef', _external=True)}}">International Patents</a></li>
        </ul>
        <ul class="list-group list-group-horizontal">
            <li class="list-group-item list-group-item-action list-group-item-myself ul-li-width flex-fill" ><a
                    href="{{url_for('pub.PubDomJournDef', _external=True)}}">Domestic Journals</a></li>
            <li
                class="list-group-item list-group-item-action list-group-item-myself ul-li-width flex-fill">
                <a href="{{url_for('pub.PubDomConfDef', _external=True)}}">Domestic Conferences</a>
            </li>
            <li class="list-group-item list-group-item-action list-group-item-myself ul-li-width flex-fill"><a
                    href="{{url_for('pub.PubDomPatenDef', _external=True)}}">Domestic Patents</a></li>
        </ul>
    </div>
    {% endif %}

    <div class="container mg-top30px">
        <h1 class="text-left border-bottom">International Journals</h1>
        <div class="row">
            {% if publicationsList %}
            {% for publication in publicationsList %}
            {% if publication.category == "International Journals" %}
            <div class="col-12 mb-4">
                <div class="card h-100">
                    <div class="card-body text-start">
                        <h5 class="card-title"><a href="{{publication.read_more}}" class="text-decoration-none" style="color: black;">{{publication.title}}</a></h5>
                        
                        {%if g.user %}
                            <ul class="name-tag-list">
                                {% for name_tag in publication.name_tags %}
                                <li>{{name_tag.user_name}}</li>
                                {% endfor %}
                            </ul>
                        <p style="border-bottom:3px solid darkgray !important;"><a href="{{url_for('pub.view_nametag',pub_id=publication.id)}}">Edit Name Tags</a></p>
                        {% else %}

                            <ul class="name-tag-list">
                                {% for name_tag in publication.name_tags %}
                                <li>{{name_tag.user_name}}</li>
                                {% endfor %}
                            </ul>

                        {% endif %}
                        <!-- author -> 컨퍼런스나 저널 이름 -->
                        <h6 class="card-subtitle mb-2 text-muted">{{publication.author}} | {{publication.date}}</h6>

                        {% if g.user %}
                        <a href="{{url_for('pub.modify', pub_id=publication.id)}}" class="btn btn-secondary">Edit</a>
                        {% endif %}
                    </div>
                </div>
            </div>
            {% endif %}
            {% endfor %}
            {% endif %}
        </div>
    </div>
</section>
{% endblock %}

pybo/templates/Publications/view_nametags.html
{% extends 'base.html' %}
{% block content %}
<header class="masthead1 bg-publication text-white text-center">
    <div class="container d-flex align-items-center flex-column">

        <!-- Masthead Heading-->
        <h1 class="masthead-heading1 text-uppercase mb-0">View NameTags</h1>
        <!-- Icon Divider-->
        <div class="divider-custom divider-light">
            <div class="divider-custom-line"></div>
            <div class="divider-custom-icon"><i class="fas fa-star"></i></div>
            <div class="divider-custom-line"></div>
        </div>

    </div>
</header>
<section>
    {% if g.user %}
    <div class="mb-3">
        <a href="{{url_for('pub.add_nametag', pub_id=publication.id)}}" class="btn btn-primary">Create Nametag</a>
    </div>
    {% endif %}
    <ul>
        {% for nametag in nametags %}
        <li><a href="{{url_for('pub.edit_nametag', pub_id=publication.id, nametag_id=nametag.id)}}">{{nametag.user_name}}</a></li>
        {% endfor %}
    </ul>
</section>
{% endblock %}