pybo/views/news_views.py
import os
from datetime import datetime
from flask import Blueprint, render_template, url_for, request,g,flash
from werkzeug.utils import redirect,secure_filename

from pybo.models import News,NewsImg
from pybo import db

from pybo.utils import save_image,delete_image, generate_unique_filename
from pybo.views.auth_views import login_required


bp = Blueprint('news',__name__,url_prefix='')

@bp.route('/News')
def NewsDef():
    newsList = News.query.order_by(News.activity_date.desc()).all()
    return render_template('News/news.html',newsList=newsList)


@bp.route('/News/create', methods=['GET','POST'])
@login_required
def create_news():
    if request.method == 'POST':
        activity_date = request.form['activity_date']
        activity = request.form['activity']
        content = request.form['content']
        images = request.files.getlist('images[]')
        create_date = datetime.now()
        new_news = News(activity_date=activity_date,activity=activity,content=content,create_date=create_date)

        for image in images:
            filename = generate_unique_filename()
            image_path = save_image(image,'news',filename)
            news_img = NewsImg(image_path=image_path,folder='news')
            new_news.images.append(news_img)
            
        db.session.add(new_news)
        db.session.commit()
        
        return redirect(url_for('news.NewsDef'))
    else:
        return render_template('News/create_news.html')

'''
@bp.route('/News/modify/<int:news_id>',methods=('GET','POST'))
@login_required
def modify(news_id):
    news = News.query.get_or_404(news_id)
    if request.method == 'POST':
        news.modify_date=datetime.now()
        db.session.commit()
        return redirect(url_for('news.NewsDef'))
    else: # GET 요청
    return render_template('News/create_news.html')
'''

@bp.route('/News/modify/<int:news_id>', methods=('GET', 'POST'))
@login_required
def modify(news_id):
    news = News.query.get_or_404(news_id)

    if request.method == 'POST':
        activity_date = request.form['activity_date']
        activity = request.form['activity']
        content = request.form['content']
        images = request.files.getlist('images[]')

        news.activity_date = activity_date
        news.activity = activity
        news.content = content

        # 기존 이미지 삭제
        for image in news.images:
            delete_image(image.folder, os.path.basename(image.image_path))
            db.session.delete(image)

        # 새로운 이미지 추가
        for image in images:
            filename=generate_unique_filename()
            image_path = save_image(image, 'news',filename)
            news_img = NewsImg(image_path=image_path, folder='news')
            news.images.append(news_img)

        news.modify_date = datetime.now()
        db.session.commit()

        return redirect(url_for('news.NewsDef'))
    else:
        return render_template('News/edit_news.html', news=news)
    

@bp.route('/News/delete/<int:news_id>')
@login_required
def delete(news_id):
    news = News.query.get_or_404(news_id)
    
    for image in news.images:
        delete_image(image.folder,os.path.basename(image.image_path))
    # news_img = NewsImg.query.filter_by(news_id=news.id).all()
    for image in news.images:
        db.session.delete(image)
    db.session.delete(news)
    db.session.commit()
    return redirect(url_for('news.NewsDef'))

pybo/templates/News/create_news.html
{% extends 'base.html' %}
{% block content %}

<!-- Masthead-->
<header class="masthead1 bg-news text-white text-center">
    <div class="container d-flex align-items-center flex-column">

        <!-- Masthead Heading-->
        <h1 class="masthead-heading1 text-uppercase mb-0">News</h1>
        <!-- Icon Divider-->
        <div class="divider-custom divider-light">
            <div class="divider-custom-line"></div>
            <div class="divider-custom-icon"><i class="fas fa-star"></i></div>
            <div class="divider-custom-line"></div>
        </div>

    </div>
</header>

<div class="container mb-3">
    <h1>Add News</h1>
    <!-- 폼 작성 -->
    <form method="POST" enctype="multipart/form-data" action="{{ url_for('news.create_news') }}">
        <div class="mb-3">
            <label for="activity_date" class="form-label">Activity Date</label>
            <input type="text" class="form-control" id="activity_date" name="activity_date" required>
        </div>
        <div class="mb-3">
            <label for="activity" class="form-label">Activity</label>
            <textarea class="form-control" id="activity" name="activity" rows="3" required></textarea>
        </div>
        <div class="mb-3">
            <label for="content" class="form-label">Content</label>
            <textarea class="form-control" id="content" name="content" rows="5"></textarea>
        </div>
        
        <div id="file-inputs">
            <div class="mb-3">
                <label for="images" class="form-label">Images</label>
                <input type="file" class="form-control" name="images[]" accept="image/*">
            </div>
        </div>
        <button type="button" id="add-file-input" class="btn btn-secondary button-19">Add more files</button>
        <button type="button" id="delete-file-input" class="btn btn-secondary button-19">Delete files</button>
        
        <button type="submit" class="btn btn-secondary button-19">Submit</button>
    </form>
</div>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
$(document).ready(function() {
    $('#add-file-input').off.click(function() {
        var newInput = $('<div class="mb-3">' +
                            '<label for="images" class="form-label">Images</label>' +
                            '<input type="file" class="form-control" name="images[]" accept="image/*">' +
                        '</div>');
        $('#file-inputs').append(newInput);
    });
});

$(document).ready(function(){
    $('#delete-file-input').click(function(){
        $('#file-inputs .mb-3:last-child').remove();
    });
});
</script>

{% endblock %}

pybo/templates/News/edit_news.html
<!-- this page is edit & delete page-->
{% extends 'base.html' %}
{% block content %}

<!-- Masthead-->
<header class="masthead1 bg-news text-white text-center">
    <div class="container d-flex align-items-center flex-column">

        <!-- Masthead Heading-->
        <h1 class="masthead-heading1 text-uppercase mb-0">Edit News</h1>
        <!-- Icon Divider-->
        <div class="divider-custom divider-light">
            <div class="divider-custom-line"></div>
            <div class="divider-custom-icon"><i class="fas fa-star"></i></div>
            <div class="divider-custom-line"></div>
        </div>

    </div>
</header>

<div class="container mb-3">
    <h1>Edit News</h1>
    <!-- 폼 작성 -->
    <form method="POST" enctype="multipart/form-data" action="{{ url_for('news.modify', news_id=news.id) }}">
        <div class="mb-3">
            <label for="activity_date" class="form-label">Activity Date</label>
            <input type="text" class="form-control" id="activity_date" name="activity_date" value="{{news.activity_date}}" required>
        </div>
        <div class="mb-3">
            <label for="activity" class="form-label">Activity</label>
            <textarea class="form-control" id="activity" name="activity" rows="3" required>{{news.activity}}</textarea>
        </div>
        <div class="mb-3">
            <label for="content" class="form-label">Content</label>
            <textarea class="form-control" id="content" name="content" rows="5">{{news.content}}</textarea>
        </div>
        
        <div id="file-inputs">
            <div class="mb-3">
                {% if news.images %}
                {% for img in news.images %}
                <label for="images" class="form-label">Images</label>
                <input type="file" class="form-control" name="images[]" accept="image/*">
                {% endfor %}
                {% endif %}
            </div>
        </div>
        <button type="button" id="add-file-input" class="btn btn-secondary button-19">Add more files</button>
        <button type="button" id="delete-file-input" class="btn btn-secondary button-19">Delete files</button>
        
        <button type="submit" class="btn btn-primary">Save Changes</button>

        <a href="javascript:void(0)" class="delete btn btn-primary" data-uri="{{url_for('news.delete',news_id=news.id)}}">delete</a>

    </form>
</div>
<!-- 이것도 왜 .off로 바꿔줘야 정상작동하는거지 ㅜㅜㅜ 원래 문법은 .off()이건데-->

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>

$(document).ready(function() {
    $('#add-file-input').off.click(function() {
        var newInput = $('<div class="mb-3">' +
                            '<label for="images" class="form-label">Images</label>' +
                            '<input type="file" class="form-control" name="images[]" accept="image/*">' +
                        '</div>');
        $('#file-inputs').append(newInput);
    });
});

$(document).ready(function(){
    $('#delete-file-input').click(function(){
        $('#file-inputs .mb-3:last-child').remove();
    });
});
</script>

{% endblock %}
{% block script %}
<script type='text/javascript'>
const delete_elements = document.getElementsByClassName("delete");
Array.from(delete_elements).forEach(function(element) {
    element.addEventListener('click', function() {
        if(confirm("정말로 삭제하시겠습니까?")) {
            location.href = this.dataset.uri;
        };
    });
});
</script>
{% endblock %}

pybo/templates/News/news.html
{% extends 'base.html' %}
{% block content %}
<!-- Masthead-->
<header class="masthead1 bg-news text-white text-center">
    <div class="container d-flex align-items-center flex-column">

        <!-- Masthead Heading-->
        <h1 class="masthead-heading1 text-uppercase mb-0">News</h1>
        <!-- Icon Divider-->
        <div class="divider-custom divider-light">
            <div class="divider-custom-line"></div>
            <div class="divider-custom-icon"><i class="fas fa-star"></i></div>
            <div class="divider-custom-line"></div>
        </div>

    </div>
</header>


<section class="py-5 text-center container d-inline">
    <div class="container">
        {% if g.user %}
        <div class="btn-wrap mb-3">
            <button class="button-19 add" role="button"><a href="{{url_for('news.create_news')}}">Create News</a></button>
        </div>
        {% endif %}
        <table class="rwd-table">
            <tbody>
                <tr>
                    <th>Date</th>
                    <th>Activity</th>
                    <th>View</th>
                    {% if g.user %}
                    <th>edit news</th>
                    {% endif %}
                </tr>
                {% if newsList %}
                {% for news in newsList %}
                <tr>
                    <td data-th="Date">
                        {{news.activity_date}}
                    </td>
                    <td data-th="LAB Activity">
                        {{news.activity}}
                    </td>
                    <td data-th="View">
                        <!-- Button trigger modal{{id}} -->
                        <button type="button" class="btn modal-btn" data-bs-toggle="modal"
                            data-bs-target="#exampleModal{{news.id}}">
                            read more
                        </button>
                        <!--modal{{id}}-->
                        <div class="modal fade" id="exampleModal{{news.id}}" tabindex="-1"
                            aria-labelledby="exampleModalLabel{{news.id}}" aria-hidden="true">
                            <div class="modal-dialog modal-xl modal-dialog-centered modal-dialog-scrollable">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h5 class="modal-title" id="exampleModalLabel{{news.id}}">{{news.activity}}</h5>
                                        <button type="button" class="btn-close" data-bs-dismiss="modal"
                                            aria-label="Close"></button>
                                    </div>
                                    <div class="modal-body">
                                        <p>{{news.content}}</p>
                                        <div class="row">
                                            <!-- img는 img만 담아둔 관계형 db 하나더 생성해서 for문으로 구성해주기!!-->
                                            {% if news.images %}
                                            {% for image in news.images %}
                                            <!--  -->
                                                <img src="{{url_for('static',filename='uploads/'+ image.folder + '/'+ image.image_path)}}" alt="activity picture" class="img-fluid">
                                            {% endfor %}
                                            {% endif %}
                                        </div>
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-secondary"
                                            data-bs-dismiss="modal">Close</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </td>
                    {% if g.user %}
                    <td>
                        <a href="{{url_for('news.modify', news_id=news.id)}}" class="btn btn-sm">edit news</a>
                    </td>
                    {% endif %}
                </tr>
                {% endfor %}
                {% endif %}
            </tbody>
        </table>
    </div>
</section>
{% endblock %}